version: '3'

services:
  sirius:
    build:
      context: .
      dockerfile: sirius.dockerfile
    restart: always
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./internal/tasks/request_logs:/internal/tasks/request_logs
      - ./internal/task_result/task_result_logs:/internal/task_result/task_result_logs
      - ./internal/server_requests/server_requests_logs:/internal/server_requests/server_requests_logs
      - ./internal/task_state/task_state_logs:/internal/task_state/task_state_logs
